/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.views.adminViews;

import java.awt.Color;

/**
 *
 * @author Alejandro
 */
public class AdminMain extends javax.swing.JFrame {
    private static AdminMain uniqueInstance = null;
    private final int[] standarColorButtons = {103,69,128};
    private final int[] hoverColorButtons = {78, 36, 102};
    /**
     * Creates new form AdminMain
     */
    public AdminMain() {
        initComponents();
    }
    
    public static AdminMain getInstance() {
        if(uniqueInstance == null) {
            uniqueInstance = new AdminMain();
        }
        return uniqueInstance;
    }
    
    private void changeBackgroundColor(java.awt.event.MouseEvent evt, int R, int G, int B) {
        evt.getComponent().setBackground(new Color(R, G, B));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftSidePanel = new javax.swing.JPanel();
        btnStudent1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStudent2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnStudent3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnStudent4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnStudent5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnStudent6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Admin View");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftSidePanel.setBackground(new java.awt.Color(65, 10, 97));
        leftSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudent1.setBackground(new java.awt.Color(103, 69, 128));
        btnStudent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudent1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudent1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStudent1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Student");

        javax.swing.GroupLayout btnStudent1Layout = new javax.swing.GroupLayout(btnStudent1);
        btnStudent1.setLayout(btnStudent1Layout);
        btnStudent1Layout.setHorizontalGroup(
            btnStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );
        btnStudent1Layout.setVerticalGroup(
            btnStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        leftSidePanel.add(btnStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, 40));

        btnStudent2.setBackground(new java.awt.Color(103, 69, 128));
        btnStudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudent2MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modify Student");

        javax.swing.GroupLayout btnStudent2Layout = new javax.swing.GroupLayout(btnStudent2);
        btnStudent2.setLayout(btnStudent2Layout);
        btnStudent2Layout.setHorizontalGroup(
            btnStudent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        btnStudent2Layout.setVerticalGroup(
            btnStudent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudent2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        leftSidePanel.add(btnStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 40));

        btnStudent3.setBackground(new java.awt.Color(103, 69, 128));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete Subject");

        javax.swing.GroupLayout btnStudent3Layout = new javax.swing.GroupLayout(btnStudent3);
        btnStudent3.setLayout(btnStudent3Layout);
        btnStudent3Layout.setHorizontalGroup(
            btnStudent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        btnStudent3Layout.setVerticalGroup(
            btnStudent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        leftSidePanel.add(btnStudent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 40));

        btnStudent4.setBackground(new java.awt.Color(103, 69, 128));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Student");

        javax.swing.GroupLayout btnStudent4Layout = new javax.swing.GroupLayout(btnStudent4);
        btnStudent4.setLayout(btnStudent4Layout);
        btnStudent4Layout.setHorizontalGroup(
            btnStudent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent4Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );
        btnStudent4Layout.setVerticalGroup(
            btnStudent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudent4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        leftSidePanel.add(btnStudent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 40));

        btnStudent5.setBackground(new java.awt.Color(103, 69, 128));
        btnStudent5.setForeground(new java.awt.Color(255, 255, 255));
        btnStudent5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudent5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudent5MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Subject");

        javax.swing.GroupLayout btnStudent5Layout = new javax.swing.GroupLayout(btnStudent5);
        btnStudent5.setLayout(btnStudent5Layout);
        btnStudent5Layout.setHorizontalGroup(
            btnStudent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent5Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(44, 44, 44))
        );
        btnStudent5Layout.setVerticalGroup(
            btnStudent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudent5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        leftSidePanel.add(btnStudent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 40));

        btnStudent6.setBackground(new java.awt.Color(103, 69, 128));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modify Subject");

        javax.swing.GroupLayout btnStudent6Layout = new javax.swing.GroupLayout(btnStudent6);
        btnStudent6.setLayout(btnStudent6Layout);
        btnStudent6Layout.setHorizontalGroup(
            btnStudent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStudent6Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );
        btnStudent6Layout.setVerticalGroup(
            btnStudent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStudent6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        leftSidePanel.add(btnStudent6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 40));

        jPanel1.add(leftSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 450));

        jPanel3.setBackground(new java.awt.Color(65, 10, 97));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 580, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudent1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent1MouseEntered
        changeBackgroundColor(evt, hoverColorButtons[0], hoverColorButtons[1], hoverColorButtons[2]);
    }//GEN-LAST:event_btnStudent1MouseEntered

    private void btnStudent1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent1MouseExited
        changeBackgroundColor(evt, standarColorButtons[0], standarColorButtons[1], standarColorButtons[2]);
    }//GEN-LAST:event_btnStudent1MouseExited

    private void btnStudent1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent1MousePressed
        CreateStudent.getInstance().setVisible(true);
        uniqueInstance.setVisible(false);
    }//GEN-LAST:event_btnStudent1MousePressed

    private void btnStudent2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent2MouseEntered
        changeBackgroundColor(evt, hoverColorButtons[0], hoverColorButtons[1], hoverColorButtons[2]);
    }//GEN-LAST:event_btnStudent2MouseEntered

    private void btnStudent5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent5MouseEntered
        changeBackgroundColor(evt, hoverColorButtons[0], hoverColorButtons[1], hoverColorButtons[2]);
    }//GEN-LAST:event_btnStudent5MouseEntered

    private void btnStudent5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent5MouseExited
        changeBackgroundColor(evt, standarColorButtons[0], standarColorButtons[1], standarColorButtons[2]);
    }//GEN-LAST:event_btnStudent5MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnStudent1;
    private javax.swing.JPanel btnStudent2;
    private javax.swing.JPanel btnStudent3;
    private javax.swing.JPanel btnStudent4;
    private javax.swing.JPanel btnStudent5;
    private javax.swing.JPanel btnStudent6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leftSidePanel;
    // End of variables declaration//GEN-END:variables
}
